---
  # Выпускаем конечный приватный ключ для сервера
- name: Generate private keys for {{ hostvars[item]['ansible_host'] }}
  community.crypto.openssl_privatekey:
    path: "../../secrets/{{ hostvars[item]['ansible_host'] }}/server.key"
    size: 2048

# На основе приватного ключа выпускаем CSR
- name: Generate CSR for {{ hostvars[item]['ansible_host'] }}
  community.crypto.openssl_csr:
    path: "../../secrets/{{ hostvars[item]['ansible_host'] }}/server.csr"
    privatekey_path: "../../secrets/{{ hostvars[item]['ansible_host'] }}/server.key"
    common_name: "{{ hostvars[item]['ansible_host'] }}"

# Подписываем приватным Root CA наш CSR и получаем сертификат для сервера
- name: Sign certificate for {{ hostvars[item]['ansible_host'] }} with Root CA
  community.crypto.x509_certificate:
    path: "../../secrets/{{ hostvars[item]['ansible_host'] }}/server.crt"
    csr_path: "../../secrets/{{ hostvars[item]['ansible_host'] }}/server.csr"
    ownca_path: "../../secrets/root_ca.crt"
    ownca_privatekey_path: "../../secrets/root_ca.key"
    provider: ownca
    ownca_not_after: "+1825d"
